name    'jdowning/wal_e'
version '0.2.2'
source 'https://github.com/justindowning/puppet-wal_e'
author 'Justin Downing'
license 'Apache License, Version 2.0'
summary 'Setup wal_e'
description 'Setup wal_e'
project_page 'https://github.com/justindowning/puppet-wal_e'

dependency 'puppetlabs/concat', '>=1.0.0 <2.0.0'
