name    'jdowning/wal_e'
version '0.1.0'
source 'https://github.com/justindowning/puppet-wal_e'
author 'Justin Donwing'
license 'Apache License, Version 2.0'
summary 'Setup wal_e'
description 'Setup wal_e'
project_page 'https://github.com/justindowning/puppet-wal_e'
## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
